### ISSUE TITLE
Adding playwright icon to Azure's official svg icon set.

### ISSUE THREAD

**Issue by mithunshanbhag** [microsoft/contosotraders-cloudtesting#196]
_[Note: Unrelated to ContosoTraders, but I wanted to file this issue before I forgot about it]_

As you're probably aware, Azure has an official svg icon set (for use in diagrams, presentations et al). 

See the bottom of this page: https://learn.microsoft.com/en-us/azure/architecture/icons/

The icons for load testing, chaos studio are already included in the icon set. 

But playwright icon is not.

![playwright](https://user-images.githubusercontent.com/2327905/229286415-0aad6ed0-b758-4937-950a-8f78e3ac5338.svg)

**Comment by MarcusFelling** [comment]
Closing, as Playwright is not an Azure service.
