### ISSUE TITLE
Add Azure Pipelines examples

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/contosotraders-cloudtesting#227]
Show GHA equivalent in Azure Pipelines 🚀

**Comment by mithunshanbhag** [comment]
Early thoughts. 

It can be done. But the tedious setup part for users will be the [github repo <-> azure devops pipeline handshake](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#access-to-github-repositories). 

Other than that....

- [Trigger conditions](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers) (on push, on PR, manual) can be handled.
- GH Secrets will be in [AZ DevOps variable groups](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
- I need to figure out how to consume output of one job in another job.
