### ISSUE TITLE
Discount codes not working

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/contosotraders-cloudtesting#230]
**Discount code** not being applied at checkout:
![image](https://user-images.githubusercontent.com/6855361/235724664-7bb34a25-3325-4e42-b0da-b888c6055649.png)

**Comment by mithunshanbhag** [comment]
Brainstorming on discount codes with @gokulsm:

1. For now, let's go with only two valid discount codes: 
   - `DISCOUNT10` = 10% off, 
   - `DISCOUNT15` = 15% off.

2. `DISCOUNT15` will be pre-applied universally to all products (whether user is logged in or not).

3. Only one coupon code can be applied at a time.

4. In the carts page, the "price" and "subtotal" columns will show the original, undiscounted prices. The cumulative discount will be shown in the order summary (in the `discount` row).

5. In the carts page, applying/removing a discount code, should update the `discount` row in the order summary.

6. On the carts page, let's eliminate the redundant `no coupons are available` message completely.

7. On the carts page, we should not allow invalid coupon codes. We should show an error (red border or something).

8. Let's also change the badge color of the accepted coupon code to green.
