### ISSUE TITLE
Unable to deploy using GitHub Action

### ISSUE THREAD

**Issue by Rickcau** [microsoft/contosotraders-cloudtesting#238]
**Describe the bug**
Did the manual thing for Cognitive Services and agreed to the responsible AI terms, but I still get a deployment failure.

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/17052492/95137e97-90f3-42d2-9694-7f540963243a)

Additional Note:
I am a CSA (rickcau@microsoft.com), I need this solution setup for a reference architecture so I can demo MALT, Playright and Chaos Studio to a customer.

When I check the RG in Azure, I can see all sorts of resources that were deployed, but the deployment is reporting as failed in GitHub.

**Comment by MarcusFelling** [comment]
Hey Rick - Can you retry the job and see if that works? Searching the error `Message: We are unable to serve this request due to an internal error` points to some GitHub Issues where retry did the trick.

**Comment by MarcusFelling** [comment]
It looks like the latest run failed. Try a new adminPassword.

`adminPassword","message":"The supplied password must be between 8-123 characters long and must satisfy at least 3 of password complexity requirements from the following:\r\n1) Contains an uppercase character\r\n2) Contains a lowercase character\r\n3) Contains a numeric digit\r\n4) Contains a special character\r\n5) Control characters are not allowed`

**Comment by mithunshanbhag** [comment]
The `adminPassword` (used for the Jumpbox VM) comes from the `SQLPASSWORD` github secret. 

For now, just changing `SQLPASSWORD` to meet the above requirements, and re-running the github workflow should do the trick.

> Background/Context/aside: We wanted to simplify the deployment setup for the user and not have them set up way too many GH secrets, variables etc. In my infinite wisdom, I decided to reuse the `SQLPASSWORD` as VM passwords too. We can revisit this decision.

**Comment by MarcusFelling** [comment]
It looks like the latest provisioning step succeeded. 

@Rickcau - Feel free to ping me in chat for any support with customer engagements. Thanks for using this repo!

**Comment by mithunshanbhag** [comment]
@Rickcau: From your [latest run](https://github.com/Rickcau/contosotraders-cloudtesting-1/actions/runs/4948044701/jobs/8848788544), I can that the provisioning succeeded, but the load test against private endppoint failed....

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/2327905/f66eecc7-c6d5-4438-a40a-5bf1f88f5e9d)

Would you mind re-running the failed job. This is a new, previously unseen error. But it may be transient in nature, and would likely pass on re-run. If not, I'd be happy to troubleshoot.
