### ISSUE TITLE
Need to remove resource group bicep hard-coded to East US

### ISSUE THREAD

**Issue by JenpOutlook** [microsoft/contosotraders-cloudtesting#250]
In the [(https://github.com/microsoft/contosotraders-cloudtesting/blob/main/iac/createResourceGroup.bicep) file we have EastUS region still hard-coded.  We need to modify to an environment variable to ensure it aligns to location user wants.  

param rgLocation string = 'eastus'

**Comment by mithunshanbhag** [comment]
Quick note: While we may be able to customize the **resource group** location based on the user's preference, we'll still be restricted on the actual **resource** locations, 

Some resource providers like chaos studio, load testing do not have full global availability yet ([details](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?regions=asia-pacific-east,asia-pacific-southeast,australia-central,australia-east,australia-southeast,brazil-south,canada-central,canada-east,central-india,china-east,china-east-2,china-non-regional,china-north,china-north-2,china-north-3,europe-north,europe-west,france-central,germany-west-central,japan-east,japan-west,korea-central,norway-east,qatar-central,south-africa-north,south-india,sweden-central,switzerland-north,uae-north,united-kingdom-south,united-kingdom-west,us-central,us-east,us-east-2,us-north-central,us-south-central,us-west,us-west-2,us-west-3,us-west-central,poland-central&products=chaos-studio,load-testing)).

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/2327905/f42a8383-3a9d-4006-8276-252cfa637a00)
