### ISSUE TITLE
Warning: path /(.*) cannot be used with pathType Prefix

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/contosotraders-cloudtesting#257]
**Describe the bug**
Fix GitHub Action Warning: Warning: path /(.*) cannot be used with pathType Prefix

**To Reproduce**
Example: https://github.com/microsoft/contosotraders-cloudtesting/actions/runs/5147171216/jobs/9267224090#step:52:164

**Screenshots**
![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/6855361/a79a8903-a7f1-4e53-89f2-e267d0c46d99)

**Comment by jerzy-wachowiak** [comment]
Solution:
https://github.com/kubernetes/ingress-nginx/issues/10200#issuecomment-1673141202
>Switching from PathPrefix to ImplementationSpecific for any path failing the validation makes the warnings go away for me.
