### ISSUE TITLE
Load testing walkthrough should include instructions for adding the required RBAC role before creating a load test

### ISSUE THREAD

**Issue by visualstuart** [microsoft/contosotraders-cloudtesting#307]
**Describe the bug**

**To Reproduce**
1. Follow the instructions in the `demo-scripts/azure-load-testing/walkthrough.md` through "Walkthrough: Creating a Load Test", step 2. Trying to "Create a Quick Test" will fail because the RBAC has not been set up and that is not discussed in the instructions

**Expected behavior**
The problem could be resolved in `demo-scripts/azure-load-testing/walkthrough.md` by providing instructions for adding the Load Test Owner (or Contributor?) role to the current user prior to the instructions for creating a load test.

**Comment by mithunshanbhag** [comment]
@visualstuart: What role does your account have at the subscription level? [Some context](https://learn.microsoft.com/en-us/azure/load-testing/how-to-assign-roles#roles-in-azure-load-testing).

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/2327905/483a3138-0cbb-41ca-8d5b-58e7bc529650)

**Comment by visualstuart** [comment]
My understanding is that this is a walkthrough which is part of a sample to help people succeed in exploring this technology. As such, this walkthrough falls short, and that can be easily fixed by adding a step in the walkthrough. The link you referenced to the "Prepare your Azure Subscription" in `docs/deployment-instructions.md` does not address adding roles to my account: step 4 is creating a service principal and adding a role to it; step 5 applies if you can't add the role to the service principal; and the other steps in this section are not about roles. This seems like a good place to insert the missing step to add or verify roles on the user's account.

My specific situation is that I am using a subscription that comes with my Visual Studio license. By default, my account has no roles in that subscription. It seems like that is a valid and perhaps relatively common situation for someone exploring the technology through this sample.

**Comment by mithunshanbhag** [comment]
>My specific situation is that I am using a subscription that comes with my Visual Studio license. By default, my account has no roles in that subscription

@visualstuart: Ah, ok thanks. That clarifies it. I'll add the required steps to the walkthrough doc today. 👍

I was mistakenly under the impression that it was the service principal account that failed to run the load test. 

PS: Thanks for filing all these issues. Highly appreciate the feedback! 😃
