### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/contosotraders-cloudtesting#308]
Go to site and click on controllers or search for anything. only loading spinner is shown and nothing loads

https://production.contosotraders.com/

<img width="1544" alt="Screenshot 2023-07-28 at 11 36 25" src="https://github.com/microsoft/contosotraders-cloudtesting/assets/13063165/d3b40d34-62eb-444d-b7cf-2ff72cea055f">

**Comment by mithunshanbhag** [comment]
@MarcusFelling: This looks related to the ingress controller changes.
https://github.com/microsoft/contosotraders-cloudtesting/pull/299

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/2327905/d6ff6c1b-9324-419e-8ea6-3c7d62079d5e)

**Comment by MarcusFelling** [comment]
> @MarcusFelling: Related to the ingress controller changes? #299
> 
> FWIW: Weirdly, this issue only repro'es in prod and NOT in staging. I'm re-deploying to prod to see if this does the trick.
> 
> ![image](https://user-images.githubusercontent.com/2327905/256836976-d6ff6c1b-9324-419e-8ea6-3c7d62079d5e.png)

No, the products API runs on App Service, not AKS. I restarted the Web App and it's working now. I had a presentation yesterday to demo load testing, so I just cleaned up in case that was the correlated.
