### ISSUE TITLE
the unknown Congnitive services  tempalte issue

### ISSUE THREAD

**Issue by zhangchl007** [microsoft/contosotraders-cloudtesting#321]
**Describe the bug**
I had already created the Congnitive services in my subscription, but I still get the issue

ResourceKindRequireAcceptTerms", "message": "This subscription cannot create CognitiveServices until you agree to Responsible AI terms for this resource.

**To Reproduce**
1. execute the contoso-traders-cloud-testing pipeline every time

**Expected behavior**
hope the issue can be fixed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser  edge
 - Version: 118.0.2088.46

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/13577471/f81a1e81-2157-4c45-84db-e7314da12157)

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/13577471/67f18e81-8073-4099-a03d-054a46bc3b88)

**Additional context**

**Comment by MarcusFelling** [comment]
Hi @zhangchl007, thank you for reporting this issue. Can you please sync your fork to the latest commits on main and try again? It looks like you're 1 commit behind:

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/6855361/a8f8f68c-7536-4378-9139-63cb446d1515)

**Comment by zhangchl007** [comment]
@MarcusFelling  many thanks, I had already merged the last commits to my branch, I saw you comment Congnitive services, many thanks!

**Comment by MarcusFelling** [comment]
Excellent!
