### ISSUE TITLE
load test failed for an private API endpoint

### ISSUE THREAD

**Issue by zhangchl007** [microsoft/contosotraders-cloudtesting#323]
**Describe the bug**
perform a testing to an private API endpoint, It look likes network unreachable
**To Reproduce**
1. follow the documents to modify the test in load test
![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/13577471/3b650234-fe07-4de7-85f7-423152db83ce)

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/13577471/cdbf4de9-d615-455c-9e02-2199fc28e17e)

2. the test result
![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/13577471/0cb54137-c9b5-4867-a2db-7e244963c196)

**Expected behavior**
expect the issue can be fixed, not sure where is the problem, I can access the intcart url from jumbox

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: edge
 - Version: 118.0.2088.46

**Additional context**

**Comment by MarcusFelling** [comment]
It looks like your domain is entered incorrectly:
![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/6855361/bb455e43-584e-4241-90e3-bedef2941539)

Please follow step 3 here: https://github.com/microsoft/contosotraders-cloudtesting/blob/main/demo-scripts/azure-load-testing/private-endpoints.md#walkthrough-modify-the-previously-created-load-test

**Comment by zhangchl007** [comment]
@MarcusFelling yes, my fault, Thanks
