### ISSUE TITLE
Bug: products not loading

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/contosotraders-cloudtesting#333]
**Describe the bug**
Seems like connection to database is down

**To Reproduce**
Open the products page or use the search bar
https://cloudtesting.contosotraders.com/list/all-products

**Expected behavior**
Should show products

**Screenshots**
Only shows loading bar
<img width="1210" alt="Screenshot 2024-03-14 at 14 27 48" src="https://github.com/microsoft/contosotraders-cloudtesting/assets/13063165/656d4db3-9018-4e95-8e78-3ecd98eb37bd">

**Comment by mithunshanbhag** [comment]
Fixed, it's working now. 

I had to delete and recreate the AKS cluster (via our github workflow) as it was in an unrecoverable state. 

Still no idea how it went into that state....

**Comment by debs-obrien** [comment]
Fantastic. Thanks for the quick response. Much appreciated
