### ISSUE TITLE
products not loading

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/contosotraders-cloudtesting#335]
Products not loading again:

similar to previous issue: https://github.com/microsoft/contosotraders-cloudtesting/issues/333

**Comment by mithunshanbhag** [comment]
Sure, I'll take a look at this tomorrow morning (am currently out of town on a work-related trip).

**Comment by mithunshanbhag** [comment]
Looks like a couple of nodes are experiencing mem saturation. Investigating....

![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/2327905/390cde81-09e1-4e1f-a424-87d93e5b7e8f)

**Comment by mithunshanbhag** [comment]
Both the test (staging) and prod clusters were exhibiting this issue. 

I've managed to revive the [staging cluster](https://staging.contosotraders.com) (by deleting it, and re-deploying it from the [Azure Devops pipeline](Both the test (staging) and prod clusters)).

Now attempting the same with the prod cluster....

**Comment by mithunshanbhag** [comment]
@sumitmalik51, @amalik99 : Someone updated the service principal details last week. 

Consequently, when the github worklow runs, the deployment happen in some other subscription (that I don't have access to).

 Do you know what's happening?
 
![image](https://github.com/microsoft/contosotraders-cloudtesting/assets/2327905/62fd1b1e-bc35-4ed4-bc39-57dc256b89ab)

**Comment by mithunshanbhag** [comment]
Aaaaand it's back online now. 

PS: I've restored the following secrets & variables to their previous values: 
- `SERVICEPRINCIPAL`
- `SUFFIX`
-  `SQLPASSWORD`
